name: OVAL Docs
markdown: kramdown
highlighter: rouge

copyright: Center for Internet Security

exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md']

redcarpet:
    extensions: ["autolink", "fenced_code_blocks", "no_intra_emphasis", "strikethrough", "superscript", "tables", "with_toc_data"]

encoding: UTF-8
